### PR TITLE
Add contact form

### PR DESCRIPTION
**Pull request by Shelob9**

### CODE REVIEW

**Comment by Shelob9** [comment]
Sorry, wrong repo. I mean, unless you want contact forms that submit against my site :)

**Comment by jasonbahl** [comment]
Glad you pushed to the wrong repo since I’m a subscriber. Really looking like CalderaQL can be a thing very soon. Looks like you already have the React side figured out. Just need to finalize the GQL part, but I think we’re actually not too far away from that too. 

Really cool

**Comment by Shelob9** [comment]
https://futurecapable.dev/contact/

It's a little gnarly, but it works, with an unmerged branch and doesn't send emails yet, but pretty good start. I will find time for a blog post about this experiment soon.

https://github.com/Shelob9/josh-dot-gatsbyjs/blob/649a7479a49db124eecbdb4e75b103b85be1cc0c/packages/gatsby-theme-twentynineteen/src/components/ContactForm.js

**Comment by m-muhsin** [comment]
Thanks for the PR! I'm working on Contact Form for this project. I think it can help. I'll take a look at the code for this.

**Pull request closed without merging**
